server:
  port: 8181

spring:
  application:
    name: deal

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5430/credit}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:13121989}
    driverClassName: org.postgresql.Driver
    hikari:
      schemas: public

  flyway:
    schemas: public
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db.migration
    user: postgres
    password: 13121989

logging:
  level:
    org:
      springframework:
        web:
          WARN
      hibernate:
        ERROR

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  model-and-view-allowed: false

feign:
  client:
    conveyor:
      url: ${FEIGN_CLIENT_URL:http://localhost:8080}
      path:
        offers: /conveyor/offers
        calculation: /conveyor/calculation