server:
  port: 8181

spring:
  application:
    name: deal

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:192.168.0.103:9092}
    producer:
      client-id: my_producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      finish-registration: finish-registration
      create-documents: create-documents
      send-documents: send-documents
      send-ses: send-ses
      credit-issued: credit-issued
      application-denied: application-denied

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5430/credit}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:13121989}
    driverClassName: org.postgresql.Driver
    hikari:
      schemas: public

  flyway:
    schemas: public
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db.migration
    user: postgres
    password: 13121989

logging:
  level:
    org:
      springframework:
        web:
          WARN
      hibernate:
        ERROR

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  model-and-view-allowed: false

feign:
  client:
    value: ${FEIGN_CLIENT_VALUE:clientFeign}
    url: ${FEIGN_CLIENT_URL:http://localhost:8080}
    path: /conveyor
