server:
  port: 8080
spring:
  application:
    name: conveyor
logging:
  level:
    org:
      springframework:
        web:
          WARN
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  model-and-view-allowed: false

