version: '3.9'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - 2181
  kafka:
    image: wurstmeister/kafka
    expose:
      - 9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "finish-registration:1:1,create-documents:1:1,send-documents:1:1,send-ses:1:1,credit-issued:1:1,application-denied:1:1"
