server:
  port: 8282
spring:
  application:
    name: application
logging:
  level:
    org:
      springframework:
        web:
          WARN
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  model-and-view-allowed: false

feign:
  client:
    deal:
      url: ${FEIGN_CLIENT_URL:http://localhost:8181}
      path:
        offer: /deal/offer
        application: /deal/application